### ISSUE TITLE
Права для SuperSales переназначать менеджеров и редактировать заказы

### ISSUE THREAD

**Issue by willmann** [willmann/dev360#13]

**Comment by Onixjfc** [comment]
Суперсейлз делать жтого не может - должны иметь возсожность перезназначать манагера и стуатусы двигать и товары редактировать (кроме оплаченных) конечно

**Comment by willmann** [comment]
Проверьте

**Comment by Onixjfc** [comment]
Совсем забыл но надо еще чтобы суперсейлз мог штрафы ставить в заказ, добавь плиз

**Comment by willmann** [comment]
Давай не будем путать задачи. Это новая задача. Мы это не обсуждали. Создай пожалуйста. Это пару минут.
