### ISSUE TITLE
Нельзя внести копеейки в стоимость товара

### ISSUE THREAD

**Issue by willmann** [willmann/dev360#19]

**Comment by willmann** [comment]
В заказе вносится, проверил.
В редактировании товара тоже.
Возможно дело в том, что в качестве разделителя надо использовать ТОЧКУ а не ЗАПЯТУЮ.

**Comment by Onixjfc** [comment]
Я имел ввиду в редаткировании товара, когда товар желтый, красный, там нельзя поставить точку или запятую, проверил на разных раскладках

**Comment by willmann** [comment]
Fixed
