### ISSUE TITLE
Разделение по группам (продажи, логистика, как в справочнике)

### ISSUE THREAD

**Issue by willmann** [willmann/dev360#2]
Чтобы выводилось и названия и сортировка по группам и подитог по деньгам

**Comment by Onixjfc** [comment]
![image](https://cloud.githubusercontent.com/assets/11632756/6848189/dc1d7bda-d3dc-11e4-8ae6-1081d48f87cd.png)

**Comment by Onixjfc** [comment]
сьезжают колонки

**Comment by willmann** [comment]
Поправили
