### ISSUE TITLE
Статусы - переключение

### ISSUE THREAD

**Issue by Onixjfc** [willmann/dev360#24]
Менедежры могут двигать статусы обратно из оплачено в те в которых можно редактировать заказы, тем самым обходя наш запрет на редактирование, что приведет к убыткам. Надо сделать так что после того как заказ побывал в оплачено, товары и услуги блокирубтся независимо от того в какой статус их двигают. Редактровать заказ могут только трасты и бухгалтерия (как сейчас) только во всех статусах после того как заказ был оплачен

**Comment by willmann** [comment]
Готово, но надо протестировать на разных группах

**Comment by Onixjfc** [comment]
Трасты и бухгалтерия пр и редактировании выскакивает debug console

**Comment by willmann** [comment]
Ooops ) Removed
