### ISSUE TITLE
Вывод единственного цвета

### ISSUE THREAD

**Issue by Onixjfc** [willmann/dev360#27]
ПРи добавлении в корзину, даже если цвет только один - его надо указывать, иначе в некоторых сериях это мешает выбрать товары, т.к. там от цвета разные шкафы к примеры и не видя выбрать не возможно

**Comment by Onixjfc** [comment]
не сделано  http://office360.ru/index.php?categoryID=10292

**Comment by willmann** [comment]
Это дубль
