### ISSUE TITLE
Зарплаты - появляется баланс- которого быть не должно

### ISSUE THREAD

**Issue by Onixjfc** [willmann/dev360#39]
Зарплаты - появляется баланс- которого быть не должно

**Comment by willmann** [comment]
Да, я заметил, что если есть отрицательный день, то и дни покрываются не полностью. Их нужно потом "доплачивать" с баланса. Разберемся

**Comment by willmann** [comment]
Fixed

**Comment by Onixjfc** [comment]
Что Fixed ? заходим в даты 15.01 - 30.01. у меня и у тебя есть баланс? откуда он берется ?

**Comment by willmann** [comment]
Если у тебя баланс был, то он никуда не делся. Почисти историю и попробуй протестировать.
