### ISSUE TITLE
Уменьшение услуг

### ISSUE THREAD

**Issue by Onixjfc** [willmann/dev360#40]
Сделать так чтобы стоимость услуг нельзя было делать в минус  и чтобы автоматос добавляла тысячу в доставку, если товаров в заказе меньше чем на 15 тыс.! - Это очень важно, т.к.к манагеры так скидки делают и не теряют проценты

**Comment by willmann** [comment]
Done

**Comment by Onixjfc** [comment]
Не сделано, что доставка 1999 когда заказ меньше чем на 15 000 р.

**Comment by willmann** [comment]
Там не было ничего про 15К. Давай создадим новую задачу.
